## Pandas - series and dataframe

In [25]:
import pandas as pd

In [26]:
#creating series
s=pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [27]:
# custom series
s=pd.Series([10,20,30],index=['a','b','c'])
print(s)
s['b']

a    10
b    20
c    30
dtype: int64

np.int64(20)

In [28]:
#create series from dictionary
data={'maths':95,'physics':88,'chemistry': 92}
type(data)
print(data)
s=pd.Series(data)
print(s)
type(s)

{'maths': 95, 'physics': 88, 'chemistry': 92}
maths        95
physics      88
chemistry    92
dtype: int64

pandas.core.series.Series

In [29]:
data={'maths':95,'physics':88,'chemistry': 92}
type(data)

dict

## Series

In [61]:
#series attributes
print(s.values) #numpy array of values
print(s.index) #index labels
#find datatype of series values
print(s.dtype)

#find type of series values
type(s)

[95 88 92]
Index(['maths', 'physics', 'chemistry'], dtype='object')
int64

pandas.core.series.Series

In [62]:
# find no of rows and cols in series
print(s.shape)

(3,)

In [63]:
print(s.size)

3

In [64]:
print(s.name)

None

In [65]:
#create a series of 10 numbers
num=pd.Series([11,12,13,12,14,15,16,17,18,19,20])
print(num)

0     11
1     12
2     13
3     12
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

In [66]:
#display first 3 elements
print(num.head(3))
print(num.tail(3))

0    11
1    12
2    13
dtype: int64
8     18
9     19
10    20
dtype: int64

In [67]:
print(num.describe())

count    11.000000
mean     15.181818
std       3.060006
min      11.000000
25%      12.500000
50%      15.000000
75%      17.500000
max      20.000000
dtype: float64

In [68]:
print(num.value_counts())

12    2
11    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
Name: count, dtype: int64

## DataFrame- two dimensional, tabular format
## Method 1: dataframe from dictionary

In [71]:
import pandas as pd
data={
    'Name':['A','B','C','D'],
    'Age':[22,22,21,23],
    'Marks':[85,92,78,95],
    'Grade':['A','A','B','A']
}
df=pd.DataFrame(data)
print(df)
type(df)

  Name  Age  Marks Grade
0    A   22     85     A
1    B   22     92     A
2    C   21     78     B
3    D   23     95     A

pandas.core.frame.DataFrame

## Method 2: from a list of dictionary

In [75]:
records=[
    {'Name':'Arjun','Dept':'CS','CGPA':8.5},
    {'Name':'Priya','Dept':'IT','CGPA':9.1},
    {'Name':'Rahul','Dept':'CS','CGPA':7.8}
]
df=pd.DataFrame(records)
print(df)

    Name Dept  CGPA
0  Arjun   CS   8.5
1  Priya   IT   9.1
2  Rahul   CS   7.8

## Method 3: from numpy array

In [79]:
import numpy as np
arr=np.array([[1,85,22],
            [2,92,25],
            [3,78,21]])
df=pd.DataFrame(arr,columns=['Rollno','Marks','Age'],index=["Row1","Row2","Row3"])
print(df)

      Rollno  Marks  Age
Row1       1     85   22
Row2       2     92   25
Row3       3     78   21

In [80]:
df.to_csv('output.csv',index=False)

## Method 4: creating dataframe from external file(csv,excel,json)

In [95]:
df1=pd.read_csv("Downloads/data.csv")

In [96]:
df1

   Rollno Name  Marks
0      11    A     20
1      12    B     18
2      13    C     19
3      14    D     22
4      15    E     21

In [97]:
df2=pd.read_excel("Downloads/data1.xlsx")

In [98]:
df2

   Rollno Name  Marks
0      11    A   20.0
1      12    B   18.0
2      13    C    NaN
3      14    D   22.0
4      15    E   21.0

## Method 5: Empty DataFrame(add data later)

In [100]:
df3=pd.DataFrame(columns=['Name','Age','Marks'])
df3

Empty DataFrame
Columns: [Name, Age, Marks]
Index: []

In [103]:
#add rows one by one
df3.loc[0]=['A',22,85]
df3.loc[1]=['B',25,92]
df3.loc[2]=['C',24,90]
print(df3)
df3

  Name  Age  Marks
0    A   22     85
1    B   25     92
2    C   24     90

  Name  Age  Marks
0    A   22     85
1    B   25     92
2    C   24     90

In [104]:
# create dataframe with tuple
tupleData=[('Mohit',1,18),('Mayuri',2,17),('Avanti',3,19)]
tupleData

[('Mohit', 1, 18), ('Mayuri', 2, 17), ('Avanti', 3, 19)]

In [121]:
df4=pd.DataFrame(tupleData,columns=["name","rollno","marks"])
df4
# display all information about the dataframe
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   rollno  3 non-null      int64
 2   marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [132]:
# create a numpy array with no range from 0 to 20
a=np.arange(20)
a
# reshape it in (5,4) matrix
# create a dataframe od the ABOVE MATRIX

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [133]:
arr=a.reshape(5,4)

In [134]:
df5=pd.DataFrame(arr,columns=['M1','M2','M3','M4'],index=["Row1","Row2","Row3","Row4","Row5"])
df5

      M1  M2  M3  M4
Row1   0   1   2   3
Row2   4   5   6   7
Row3   8   9  10  11
Row4  12  13  14  15
Row5  16  17  18  19